/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.usecase.usecasedsl.ExtensionSubStep;
import org.usecase.usecasedsl.UsecasedslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Extension Sub Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl#getNumber <em>Number</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl#getSubnumber <em>Subnumber</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl#getText <em>Text</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExtensionSubStepImpl extends MinimalEObjectImpl.Container implements ExtensionSubStep
{
  /**
   * The default value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected int number = NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected static final String LETTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected String letter = LETTER_EDEFAULT;

  /**
   * The default value of the '{@link #getSubnumber() <em>Subnumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubnumber()
   * @generated
   * @ordered
   */
  protected static final int SUBNUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSubnumber() <em>Subnumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubnumber()
   * @generated
   * @ordered
   */
  protected int subnumber = SUBNUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected static final String TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected String text = TEXT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExtensionSubStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsecasedslPackage.Literals.EXTENSION_SUB_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumber()
  {
    return number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber(int newNumber)
  {
    int oldNumber = number;
    number = newNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_SUB_STEP__NUMBER, oldNumber, number));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLetter()
  {
    return letter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLetter(String newLetter)
  {
    String oldLetter = letter;
    letter = newLetter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_SUB_STEP__LETTER, oldLetter, letter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSubnumber()
  {
    return subnumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubnumber(int newSubnumber)
  {
    int oldSubnumber = subnumber;
    subnumber = newSubnumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_SUB_STEP__SUBNUMBER, oldSubnumber, subnumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setText(String newText)
  {
    String oldText = text;
    text = newText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_SUB_STEP__TEXT, oldText, text));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_SUB_STEP__NUMBER:
        return getNumber();
      case UsecasedslPackage.EXTENSION_SUB_STEP__LETTER:
        return getLetter();
      case UsecasedslPackage.EXTENSION_SUB_STEP__SUBNUMBER:
        return getSubnumber();
      case UsecasedslPackage.EXTENSION_SUB_STEP__TEXT:
        return getText();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_SUB_STEP__NUMBER:
        setNumber((Integer)newValue);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__LETTER:
        setLetter((String)newValue);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__SUBNUMBER:
        setSubnumber((Integer)newValue);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__TEXT:
        setText((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_SUB_STEP__NUMBER:
        setNumber(NUMBER_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__LETTER:
        setLetter(LETTER_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__SUBNUMBER:
        setSubnumber(SUBNUMBER_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_SUB_STEP__TEXT:
        setText(TEXT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_SUB_STEP__NUMBER:
        return number != NUMBER_EDEFAULT;
      case UsecasedslPackage.EXTENSION_SUB_STEP__LETTER:
        return LETTER_EDEFAULT == null ? letter != null : !LETTER_EDEFAULT.equals(letter);
      case UsecasedslPackage.EXTENSION_SUB_STEP__SUBNUMBER:
        return subnumber != SUBNUMBER_EDEFAULT;
      case UsecasedslPackage.EXTENSION_SUB_STEP__TEXT:
        return TEXT_EDEFAULT == null ? text != null : !TEXT_EDEFAULT.equals(text);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (number: ");
    result.append(number);
    result.append(", letter: ");
    result.append(letter);
    result.append(", subnumber: ");
    result.append(subnumber);
    result.append(", text: ");
    result.append(text);
    result.append(')');
    return result.toString();
  }

} //ExtensionSubStepImpl
