/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.usecase.usecasedsl.ExtensionStep;
import org.usecase.usecasedsl.ExtensionSubStep;
import org.usecase.usecasedsl.UsecasedslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Extension Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionStepImpl#getNumber <em>Number</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionStepImpl#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionStepImpl#getText <em>Text</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.ExtensionStepImpl#getSubsteps <em>Substeps</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExtensionStepImpl extends MinimalEObjectImpl.Container implements ExtensionStep
{
  /**
   * The default value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected int number = NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected static final String LETTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected String letter = LETTER_EDEFAULT;

  /**
   * The default value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected static final String TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected String text = TEXT_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubsteps() <em>Substeps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsteps()
   * @generated
   * @ordered
   */
  protected EList<ExtensionSubStep> substeps;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExtensionStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsecasedslPackage.Literals.EXTENSION_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumber()
  {
    return number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber(int newNumber)
  {
    int oldNumber = number;
    number = newNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_STEP__NUMBER, oldNumber, number));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLetter()
  {
    return letter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLetter(String newLetter)
  {
    String oldLetter = letter;
    letter = newLetter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_STEP__LETTER, oldLetter, letter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setText(String newText)
  {
    String oldText = text;
    text = newText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.EXTENSION_STEP__TEXT, oldText, text));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExtensionSubStep> getSubsteps()
  {
    if (substeps == null)
    {
      substeps = new EObjectContainmentEList<ExtensionSubStep>(ExtensionSubStep.class, this, UsecasedslPackage.EXTENSION_STEP__SUBSTEPS);
    }
    return substeps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_STEP__SUBSTEPS:
        return ((InternalEList<?>)getSubsteps()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_STEP__NUMBER:
        return getNumber();
      case UsecasedslPackage.EXTENSION_STEP__LETTER:
        return getLetter();
      case UsecasedslPackage.EXTENSION_STEP__TEXT:
        return getText();
      case UsecasedslPackage.EXTENSION_STEP__SUBSTEPS:
        return getSubsteps();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_STEP__NUMBER:
        setNumber((Integer)newValue);
        return;
      case UsecasedslPackage.EXTENSION_STEP__LETTER:
        setLetter((String)newValue);
        return;
      case UsecasedslPackage.EXTENSION_STEP__TEXT:
        setText((String)newValue);
        return;
      case UsecasedslPackage.EXTENSION_STEP__SUBSTEPS:
        getSubsteps().clear();
        getSubsteps().addAll((Collection<? extends ExtensionSubStep>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_STEP__NUMBER:
        setNumber(NUMBER_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_STEP__LETTER:
        setLetter(LETTER_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_STEP__TEXT:
        setText(TEXT_EDEFAULT);
        return;
      case UsecasedslPackage.EXTENSION_STEP__SUBSTEPS:
        getSubsteps().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.EXTENSION_STEP__NUMBER:
        return number != NUMBER_EDEFAULT;
      case UsecasedslPackage.EXTENSION_STEP__LETTER:
        return LETTER_EDEFAULT == null ? letter != null : !LETTER_EDEFAULT.equals(letter);
      case UsecasedslPackage.EXTENSION_STEP__TEXT:
        return TEXT_EDEFAULT == null ? text != null : !TEXT_EDEFAULT.equals(text);
      case UsecasedslPackage.EXTENSION_STEP__SUBSTEPS:
        return substeps != null && !substeps.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (number: ");
    result.append(number);
    result.append(", letter: ");
    result.append(letter);
    result.append(", text: ");
    result.append(text);
    result.append(')');
    return result.toString();
  }

} //ExtensionStepImpl
