/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.usecase.usecasedsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UsecasedslFactoryImpl extends EFactoryImpl implements UsecasedslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static UsecasedslFactory init()
  {
    try
    {
      UsecasedslFactory theUsecasedslFactory = (UsecasedslFactory)EPackage.Registry.INSTANCE.getEFactory(UsecasedslPackage.eNS_URI);
      if (theUsecasedslFactory != null)
      {
        return theUsecasedslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new UsecasedslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UsecasedslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION: return createUseCaseDescription();
      case UsecasedslPackage.BULLET_ITEM: return createBulletItem();
      case UsecasedslPackage.NUMBERED_STEP: return createNumberedStep();
      case UsecasedslPackage.EXTENSION_STEP: return createExtensionStep();
      case UsecasedslPackage.EXTENSION_SUB_STEP: return createExtensionSubStep();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UseCaseDescription createUseCaseDescription()
  {
    UseCaseDescriptionImpl useCaseDescription = new UseCaseDescriptionImpl();
    return useCaseDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BulletItem createBulletItem()
  {
    BulletItemImpl bulletItem = new BulletItemImpl();
    return bulletItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumberedStep createNumberedStep()
  {
    NumberedStepImpl numberedStep = new NumberedStepImpl();
    return numberedStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExtensionStep createExtensionStep()
  {
    ExtensionStepImpl extensionStep = new ExtensionStepImpl();
    return extensionStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExtensionSubStep createExtensionSubStep()
  {
    ExtensionSubStepImpl extensionSubStep = new ExtensionSubStepImpl();
    return extensionSubStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsecasedslPackage getUsecasedslPackage()
  {
    return (UsecasedslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static UsecasedslPackage getPackage()
  {
    return UsecasedslPackage.eINSTANCE;
  }

} //UsecasedslFactoryImpl
