/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.usecase.usecasedsl.BulletItem;
import org.usecase.usecasedsl.ExtensionStep;
import org.usecase.usecasedsl.NumberedStep;
import org.usecase.usecasedsl.UseCaseDescription;
import org.usecase.usecasedsl.UsecasedslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Use Case Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getPrimaryActor <em>Primary Actor</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getStakeholders <em>Stakeholders</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getPostconditions <em>Postconditions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getMainSteps <em>Main Steps</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getExtensions <em>Extensions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getSpecialRequirements <em>Special Requirements</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getTechnologyVariations <em>Technology Variations</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getFrequency <em>Frequency</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl#getOpenIssues <em>Open Issues</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UseCaseDescriptionImpl extends MinimalEObjectImpl.Container implements UseCaseDescription
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPrimaryActor() <em>Primary Actor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimaryActor()
   * @generated
   * @ordered
   */
  protected static final String PRIMARY_ACTOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrimaryActor() <em>Primary Actor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimaryActor()
   * @generated
   * @ordered
   */
  protected String primaryActor = PRIMARY_ACTOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getStakeholders() <em>Stakeholders</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStakeholders()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> stakeholders;

  /**
   * The cached value of the '{@link #getPreconditions() <em>Preconditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreconditions()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> preconditions;

  /**
   * The cached value of the '{@link #getPostconditions() <em>Postconditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostconditions()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> postconditions;

  /**
   * The cached value of the '{@link #getMainSteps() <em>Main Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMainSteps()
   * @generated
   * @ordered
   */
  protected EList<NumberedStep> mainSteps;

  /**
   * The cached value of the '{@link #getExtensions() <em>Extensions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtensions()
   * @generated
   * @ordered
   */
  protected EList<ExtensionStep> extensions;

  /**
   * The cached value of the '{@link #getSpecialRequirements() <em>Special Requirements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecialRequirements()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> specialRequirements;

  /**
   * The cached value of the '{@link #getTechnologyVariations() <em>Technology Variations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTechnologyVariations()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> technologyVariations;

  /**
   * The default value of the '{@link #getFrequency() <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrequency()
   * @generated
   * @ordered
   */
  protected static final String FREQUENCY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFrequency() <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrequency()
   * @generated
   * @ordered
   */
  protected String frequency = FREQUENCY_EDEFAULT;

  /**
   * The cached value of the '{@link #getOpenIssues() <em>Open Issues</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpenIssues()
   * @generated
   * @ordered
   */
  protected EList<BulletItem> openIssues;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UseCaseDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsecasedslPackage.Literals.USE_CASE_DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.USE_CASE_DESCRIPTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPrimaryActor()
  {
    return primaryActor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrimaryActor(String newPrimaryActor)
  {
    String oldPrimaryActor = primaryActor;
    primaryActor = newPrimaryActor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.USE_CASE_DESCRIPTION__PRIMARY_ACTOR, oldPrimaryActor, primaryActor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getStakeholders()
  {
    if (stakeholders == null)
    {
      stakeholders = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS);
    }
    return stakeholders;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getPreconditions()
  {
    if (preconditions == null)
    {
      preconditions = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS);
    }
    return preconditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getPostconditions()
  {
    if (postconditions == null)
    {
      postconditions = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS);
    }
    return postconditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<NumberedStep> getMainSteps()
  {
    if (mainSteps == null)
    {
      mainSteps = new EObjectContainmentEList<NumberedStep>(NumberedStep.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS);
    }
    return mainSteps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExtensionStep> getExtensions()
  {
    if (extensions == null)
    {
      extensions = new EObjectContainmentEList<ExtensionStep>(ExtensionStep.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS);
    }
    return extensions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getSpecialRequirements()
  {
    if (specialRequirements == null)
    {
      specialRequirements = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS);
    }
    return specialRequirements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getTechnologyVariations()
  {
    if (technologyVariations == null)
    {
      technologyVariations = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS);
    }
    return technologyVariations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFrequency()
  {
    return frequency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFrequency(String newFrequency)
  {
    String oldFrequency = frequency;
    frequency = newFrequency;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsecasedslPackage.USE_CASE_DESCRIPTION__FREQUENCY, oldFrequency, frequency));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BulletItem> getOpenIssues()
  {
    if (openIssues == null)
    {
      openIssues = new EObjectContainmentEList<BulletItem>(BulletItem.class, this, UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES);
    }
    return openIssues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS:
        return ((InternalEList<?>)getStakeholders()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS:
        return ((InternalEList<?>)getPreconditions()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS:
        return ((InternalEList<?>)getPostconditions()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS:
        return ((InternalEList<?>)getMainSteps()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS:
        return ((InternalEList<?>)getExtensions()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS:
        return ((InternalEList<?>)getSpecialRequirements()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS:
        return ((InternalEList<?>)getTechnologyVariations()).basicRemove(otherEnd, msgs);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES:
        return ((InternalEList<?>)getOpenIssues()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION__NAME:
        return getName();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRIMARY_ACTOR:
        return getPrimaryActor();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS:
        return getStakeholders();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS:
        return getPreconditions();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS:
        return getPostconditions();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS:
        return getMainSteps();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS:
        return getExtensions();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS:
        return getSpecialRequirements();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS:
        return getTechnologyVariations();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__FREQUENCY:
        return getFrequency();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES:
        return getOpenIssues();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION__NAME:
        setName((String)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRIMARY_ACTOR:
        setPrimaryActor((String)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS:
        getStakeholders().clear();
        getStakeholders().addAll((Collection<? extends BulletItem>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS:
        getPreconditions().clear();
        getPreconditions().addAll((Collection<? extends BulletItem>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS:
        getPostconditions().clear();
        getPostconditions().addAll((Collection<? extends BulletItem>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS:
        getMainSteps().clear();
        getMainSteps().addAll((Collection<? extends NumberedStep>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS:
        getExtensions().clear();
        getExtensions().addAll((Collection<? extends ExtensionStep>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS:
        getSpecialRequirements().clear();
        getSpecialRequirements().addAll((Collection<? extends BulletItem>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS:
        getTechnologyVariations().clear();
        getTechnologyVariations().addAll((Collection<? extends BulletItem>)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__FREQUENCY:
        setFrequency((String)newValue);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES:
        getOpenIssues().clear();
        getOpenIssues().addAll((Collection<? extends BulletItem>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRIMARY_ACTOR:
        setPrimaryActor(PRIMARY_ACTOR_EDEFAULT);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS:
        getStakeholders().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS:
        getPreconditions().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS:
        getPostconditions().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS:
        getMainSteps().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS:
        getExtensions().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS:
        getSpecialRequirements().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS:
        getTechnologyVariations().clear();
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__FREQUENCY:
        setFrequency(FREQUENCY_EDEFAULT);
        return;
      case UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES:
        getOpenIssues().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsecasedslPackage.USE_CASE_DESCRIPTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRIMARY_ACTOR:
        return PRIMARY_ACTOR_EDEFAULT == null ? primaryActor != null : !PRIMARY_ACTOR_EDEFAULT.equals(primaryActor);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__STAKEHOLDERS:
        return stakeholders != null && !stakeholders.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__PRECONDITIONS:
        return preconditions != null && !preconditions.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__POSTCONDITIONS:
        return postconditions != null && !postconditions.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__MAIN_STEPS:
        return mainSteps != null && !mainSteps.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__EXTENSIONS:
        return extensions != null && !extensions.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS:
        return specialRequirements != null && !specialRequirements.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS:
        return technologyVariations != null && !technologyVariations.isEmpty();
      case UsecasedslPackage.USE_CASE_DESCRIPTION__FREQUENCY:
        return FREQUENCY_EDEFAULT == null ? frequency != null : !FREQUENCY_EDEFAULT.equals(frequency);
      case UsecasedslPackage.USE_CASE_DESCRIPTION__OPEN_ISSUES:
        return openIssues != null && !openIssues.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", primaryActor: ");
    result.append(primaryActor);
    result.append(", frequency: ");
    result.append(frequency);
    result.append(')');
    return result.toString();
  }

} //UseCaseDescriptionImpl
