/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.usecase.usecasedsl.BulletItem;
import org.usecase.usecasedsl.ExtensionStep;
import org.usecase.usecasedsl.ExtensionSubStep;
import org.usecase.usecasedsl.NumberedStep;
import org.usecase.usecasedsl.UseCaseDescription;
import org.usecase.usecasedsl.UsecasedslFactory;
import org.usecase.usecasedsl.UsecasedslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UsecasedslPackageImpl extends EPackageImpl implements UsecasedslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass useCaseDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bulletItemEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numberedStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass extensionStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass extensionSubStepEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.usecase.usecasedsl.UsecasedslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private UsecasedslPackageImpl()
  {
    super(eNS_URI, UsecasedslFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link UsecasedslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static UsecasedslPackage init()
  {
    if (isInited) return (UsecasedslPackage)EPackage.Registry.INSTANCE.getEPackage(UsecasedslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredUsecasedslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    UsecasedslPackageImpl theUsecasedslPackage = registeredUsecasedslPackage instanceof UsecasedslPackageImpl ? (UsecasedslPackageImpl)registeredUsecasedslPackage : new UsecasedslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theUsecasedslPackage.createPackageContents();

    // Initialize created meta-data
    theUsecasedslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theUsecasedslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(UsecasedslPackage.eNS_URI, theUsecasedslPackage);
    return theUsecasedslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUseCaseDescription()
  {
    return useCaseDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDescription_Name()
  {
    return (EAttribute)useCaseDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDescription_PrimaryActor()
  {
    return (EAttribute)useCaseDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_Stakeholders()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_Preconditions()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_Postconditions()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_MainSteps()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_Extensions()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_SpecialRequirements()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_TechnologyVariations()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDescription_Frequency()
  {
    return (EAttribute)useCaseDescriptionEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUseCaseDescription_OpenIssues()
  {
    return (EReference)useCaseDescriptionEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBulletItem()
  {
    return bulletItemEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBulletItem_Text()
  {
    return (EAttribute)bulletItemEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNumberedStep()
  {
    return numberedStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumberedStep_Number()
  {
    return (EAttribute)numberedStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumberedStep_Text()
  {
    return (EAttribute)numberedStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExtensionStep()
  {
    return extensionStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionStep_Number()
  {
    return (EAttribute)extensionStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionStep_Letter()
  {
    return (EAttribute)extensionStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionStep_Text()
  {
    return (EAttribute)extensionStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExtensionStep_Substeps()
  {
    return (EReference)extensionStepEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExtensionSubStep()
  {
    return extensionSubStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionSubStep_Number()
  {
    return (EAttribute)extensionSubStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionSubStep_Letter()
  {
    return (EAttribute)extensionSubStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionSubStep_Subnumber()
  {
    return (EAttribute)extensionSubStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtensionSubStep_Text()
  {
    return (EAttribute)extensionSubStepEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsecasedslFactory getUsecasedslFactory()
  {
    return (UsecasedslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    useCaseDescriptionEClass = createEClass(USE_CASE_DESCRIPTION);
    createEAttribute(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__NAME);
    createEAttribute(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__PRIMARY_ACTOR);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__STAKEHOLDERS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__PRECONDITIONS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__POSTCONDITIONS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__MAIN_STEPS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__EXTENSIONS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS);
    createEAttribute(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__FREQUENCY);
    createEReference(useCaseDescriptionEClass, USE_CASE_DESCRIPTION__OPEN_ISSUES);

    bulletItemEClass = createEClass(BULLET_ITEM);
    createEAttribute(bulletItemEClass, BULLET_ITEM__TEXT);

    numberedStepEClass = createEClass(NUMBERED_STEP);
    createEAttribute(numberedStepEClass, NUMBERED_STEP__NUMBER);
    createEAttribute(numberedStepEClass, NUMBERED_STEP__TEXT);

    extensionStepEClass = createEClass(EXTENSION_STEP);
    createEAttribute(extensionStepEClass, EXTENSION_STEP__NUMBER);
    createEAttribute(extensionStepEClass, EXTENSION_STEP__LETTER);
    createEAttribute(extensionStepEClass, EXTENSION_STEP__TEXT);
    createEReference(extensionStepEClass, EXTENSION_STEP__SUBSTEPS);

    extensionSubStepEClass = createEClass(EXTENSION_SUB_STEP);
    createEAttribute(extensionSubStepEClass, EXTENSION_SUB_STEP__NUMBER);
    createEAttribute(extensionSubStepEClass, EXTENSION_SUB_STEP__LETTER);
    createEAttribute(extensionSubStepEClass, EXTENSION_SUB_STEP__SUBNUMBER);
    createEAttribute(extensionSubStepEClass, EXTENSION_SUB_STEP__TEXT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(useCaseDescriptionEClass, UseCaseDescription.class, "UseCaseDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUseCaseDescription_Name(), ecorePackage.getEString(), "name", null, 0, 1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUseCaseDescription_PrimaryActor(), ecorePackage.getEString(), "primaryActor", null, 0, 1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_Stakeholders(), this.getBulletItem(), null, "stakeholders", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_Preconditions(), this.getBulletItem(), null, "preconditions", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_Postconditions(), this.getBulletItem(), null, "postconditions", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_MainSteps(), this.getNumberedStep(), null, "mainSteps", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_Extensions(), this.getExtensionStep(), null, "extensions", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_SpecialRequirements(), this.getBulletItem(), null, "specialRequirements", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_TechnologyVariations(), this.getBulletItem(), null, "technologyVariations", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUseCaseDescription_Frequency(), ecorePackage.getEString(), "frequency", null, 0, 1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUseCaseDescription_OpenIssues(), this.getBulletItem(), null, "openIssues", null, 0, -1, UseCaseDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(bulletItemEClass, BulletItem.class, "BulletItem", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBulletItem_Text(), ecorePackage.getEString(), "text", null, 0, 1, BulletItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numberedStepEClass, NumberedStep.class, "NumberedStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNumberedStep_Number(), ecorePackage.getEInt(), "number", null, 0, 1, NumberedStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNumberedStep_Text(), ecorePackage.getEString(), "text", null, 0, 1, NumberedStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(extensionStepEClass, ExtensionStep.class, "ExtensionStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExtensionStep_Number(), ecorePackage.getEInt(), "number", null, 0, 1, ExtensionStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtensionStep_Letter(), ecorePackage.getEString(), "letter", null, 0, 1, ExtensionStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtensionStep_Text(), ecorePackage.getEString(), "text", null, 0, 1, ExtensionStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExtensionStep_Substeps(), this.getExtensionSubStep(), null, "substeps", null, 0, -1, ExtensionStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(extensionSubStepEClass, ExtensionSubStep.class, "ExtensionSubStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExtensionSubStep_Number(), ecorePackage.getEInt(), "number", null, 0, 1, ExtensionSubStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtensionSubStep_Letter(), ecorePackage.getEString(), "letter", null, 0, 1, ExtensionSubStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtensionSubStep_Subnumber(), ecorePackage.getEInt(), "subnumber", null, 0, 1, ExtensionSubStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtensionSubStep_Text(), ecorePackage.getEString(), "text", null, 0, 1, ExtensionSubStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //UsecasedslPackageImpl
