/*
 * generated by Xtext 2.34.0
 */
package org.usecase.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.usecase.parser.antlr.internal.InternalUseCaseDslParser;
import org.usecase.services.UseCaseDslGrammarAccess;

public class UseCaseDslParser extends AbstractAntlrParser {

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUseCaseDslParser createParser(XtextTokenStream stream) {
		return new InternalUseCaseDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "UseCaseDescription";
	}

	public UseCaseDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UseCaseDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
