/*
 * generated by Xtext 2.34.0
 */
package org.usecase;

import org.eclipse.xtext.validation.IResourceValidator;
import org.usecase.validation.UseCaseDslValidator;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UseCaseDslRuntimeModule extends AbstractUseCaseDslRuntimeModule {
}
