/*
 * generated by Xtext 2.34.0
 */
package org.usecase;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UseCaseDescStandaloneSetup extends UseCaseDescStandaloneSetupGenerated {

	public static void doSetup() {
		new UseCaseDescStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
