/*
 * generated by Xtext 2.34.0
 */
package org.usecase;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UseCaseDslStandaloneSetup extends UseCaseDslStandaloneSetupGenerated {

	public static void doSetup() {
		new UseCaseDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
