/*
 * generated by Xtext 2.34.0
 */
package org.usecase.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.usecase.services.UseCaseDslGrammarAccess;
import org.usecase.usecasedesc.Model;
import org.usecase.usecasedesc.UseCaseDesc;
import org.usecase.usecasedesc.UsecasedescPackage;

@SuppressWarnings("all")
public class UseCaseDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == UsecasedescPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case UsecasedescPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case UsecasedescPackage.USE_CASE_DESC:
				sequence_UseCaseDesc(context, (UseCaseDesc) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     usecases+=UseCaseDesc+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UseCaseDesc returns UseCaseDesc
	 *
	 * Constraint:
	 *     (name=ID actor=ID descripcion=STRING)
	 * </pre>
	 */
	protected void sequence_UseCaseDesc(ISerializationContext context, UseCaseDesc semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__NAME));
			if (transientValues.isValueTransient(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__ACTOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__ACTOR));
			if (transientValues.isValueTransient(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__DESCRIPCION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedescPackage.Literals.USE_CASE_DESC__DESCRIPCION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUseCaseDescAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getUseCaseDescAccess().getActorIDTerminalRuleCall_3_0(), semanticObject.getActor());
		feeder.accept(grammarAccess.getUseCaseDescAccess().getDescripcionSTRINGTerminalRuleCall_5_0(), semanticObject.getDescripcion());
		feeder.finish();
	}
	
	
}
