/*
 * generated by Xtext 2.34.0
 */
package org.usecase.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.usecase.services.UseCaseDslGrammarAccess;
import org.usecase.usecasedsl.BulletItem;
import org.usecase.usecasedsl.ExtensionStep;
import org.usecase.usecasedsl.ExtensionSubStep;
import org.usecase.usecasedsl.NumberedStep;
import org.usecase.usecasedsl.UseCaseDescription;
import org.usecase.usecasedsl.UsecasedslPackage;

@SuppressWarnings("all")
public class UseCaseDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == UsecasedslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case UsecasedslPackage.BULLET_ITEM:
				sequence_BulletItem(context, (BulletItem) semanticObject); 
				return; 
			case UsecasedslPackage.EXTENSION_STEP:
				sequence_ExtensionStep(context, (ExtensionStep) semanticObject); 
				return; 
			case UsecasedslPackage.EXTENSION_SUB_STEP:
				sequence_ExtensionSubStep(context, (ExtensionSubStep) semanticObject); 
				return; 
			case UsecasedslPackage.NUMBERED_STEP:
				sequence_NumberedStep(context, (NumberedStep) semanticObject); 
				return; 
			case UsecasedslPackage.USE_CASE_DESCRIPTION:
				sequence_UseCaseDescription(context, (UseCaseDescription) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     BulletItem returns BulletItem
	 *
	 * Constraint:
	 *     text=STRING
	 * </pre>
	 */
	protected void sequence_BulletItem(ISerializationContext context, BulletItem semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.BULLET_ITEM__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.BULLET_ITEM__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBulletItemAccess().getTextSTRINGTerminalRuleCall_1_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExtensionStep returns ExtensionStep
	 *
	 * Constraint:
	 *     (number=INT letter=ID text=STRING substeps+=ExtensionSubStep*)
	 * </pre>
	 */
	protected void sequence_ExtensionStep(ISerializationContext context, ExtensionStep semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExtensionSubStep returns ExtensionSubStep
	 *
	 * Constraint:
	 *     (number=INT letter=ID subnumber=INT text=STRING)
	 * </pre>
	 */
	protected void sequence_ExtensionSubStep(ISerializationContext context, ExtensionSubStep semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__NUMBER));
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__LETTER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__LETTER));
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__SUBNUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__SUBNUMBER));
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.EXTENSION_SUB_STEP__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExtensionSubStepAccess().getNumberINTTerminalRuleCall_0_0(), semanticObject.getNumber());
		feeder.accept(grammarAccess.getExtensionSubStepAccess().getLetterIDTerminalRuleCall_1_0(), semanticObject.getLetter());
		feeder.accept(grammarAccess.getExtensionSubStepAccess().getSubnumberINTTerminalRuleCall_3_0(), semanticObject.getSubnumber());
		feeder.accept(grammarAccess.getExtensionSubStepAccess().getTextSTRINGTerminalRuleCall_5_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     NumberedStep returns NumberedStep
	 *
	 * Constraint:
	 *     (number=INT text=STRING)
	 * </pre>
	 */
	protected void sequence_NumberedStep(ISerializationContext context, NumberedStep semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.NUMBERED_STEP__NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.NUMBERED_STEP__NUMBER));
			if (transientValues.isValueTransient(semanticObject, UsecasedslPackage.Literals.NUMBERED_STEP__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UsecasedslPackage.Literals.NUMBERED_STEP__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNumberedStepAccess().getNumberINTTerminalRuleCall_0_0(), semanticObject.getNumber());
		feeder.accept(grammarAccess.getNumberedStepAccess().getTextSTRINGTerminalRuleCall_2_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UseCaseDescription returns UseCaseDescription
	 *
	 * Constraint:
	 *     (
	 *         name=STRING 
	 *         primaryActor=STRING 
	 *         stakeholders+=BulletItem* 
	 *         preconditions+=BulletItem* 
	 *         postconditions+=BulletItem* 
	 *         mainSteps+=NumberedStep* 
	 *         extensions+=ExtensionStep* 
	 *         specialRequirements+=BulletItem* 
	 *         technologyVariations+=BulletItem* 
	 *         frequency=STRING 
	 *         openIssues+=BulletItem*
	 *     )
	 * </pre>
	 */
	protected void sequence_UseCaseDescription(ISerializationContext context, UseCaseDescription semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
