/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.usecase.ide.contentassist.antlr.internal.InternalUseCaseDslParser;
import org.usecase.services.UseCaseDslGrammarAccess;

public class UseCaseDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UseCaseDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UseCaseDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getGroup(), "rule__UseCaseDescription__Group__0");
			builder.put(grammarAccess.getBulletItemAccess().getGroup(), "rule__BulletItem__Group__0");
			builder.put(grammarAccess.getNumberedStepAccess().getGroup(), "rule__NumberedStep__Group__0");
			builder.put(grammarAccess.getExtensionStepAccess().getGroup(), "rule__ExtensionStep__Group__0");
			builder.put(grammarAccess.getExtensionSubStepAccess().getGroup(), "rule__ExtensionSubStep__Group__0");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getNameAssignment_1(), "rule__UseCaseDescription__NameAssignment_1");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getPrimaryActorAssignment_3(), "rule__UseCaseDescription__PrimaryActorAssignment_3");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getStakeholdersAssignment_5(), "rule__UseCaseDescription__StakeholdersAssignment_5");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getPreconditionsAssignment_7(), "rule__UseCaseDescription__PreconditionsAssignment_7");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getPostconditionsAssignment_9(), "rule__UseCaseDescription__PostconditionsAssignment_9");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getMainStepsAssignment_11(), "rule__UseCaseDescription__MainStepsAssignment_11");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getExtensionsAssignment_13(), "rule__UseCaseDescription__ExtensionsAssignment_13");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getSpecialRequirementsAssignment_15(), "rule__UseCaseDescription__SpecialRequirementsAssignment_15");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getTechnologyVariationsAssignment_17(), "rule__UseCaseDescription__TechnologyVariationsAssignment_17");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getFrequencyAssignment_19(), "rule__UseCaseDescription__FrequencyAssignment_19");
			builder.put(grammarAccess.getUseCaseDescriptionAccess().getOpenIssuesAssignment_21(), "rule__UseCaseDescription__OpenIssuesAssignment_21");
			builder.put(grammarAccess.getBulletItemAccess().getTextAssignment_1(), "rule__BulletItem__TextAssignment_1");
			builder.put(grammarAccess.getNumberedStepAccess().getNumberAssignment_0(), "rule__NumberedStep__NumberAssignment_0");
			builder.put(grammarAccess.getNumberedStepAccess().getTextAssignment_2(), "rule__NumberedStep__TextAssignment_2");
			builder.put(grammarAccess.getExtensionStepAccess().getNumberAssignment_0(), "rule__ExtensionStep__NumberAssignment_0");
			builder.put(grammarAccess.getExtensionStepAccess().getLetterAssignment_1(), "rule__ExtensionStep__LetterAssignment_1");
			builder.put(grammarAccess.getExtensionStepAccess().getTextAssignment_3(), "rule__ExtensionStep__TextAssignment_3");
			builder.put(grammarAccess.getExtensionStepAccess().getSubstepsAssignment_4(), "rule__ExtensionStep__SubstepsAssignment_4");
			builder.put(grammarAccess.getExtensionSubStepAccess().getNumberAssignment_0(), "rule__ExtensionSubStep__NumberAssignment_0");
			builder.put(grammarAccess.getExtensionSubStepAccess().getLetterAssignment_1(), "rule__ExtensionSubStep__LetterAssignment_1");
			builder.put(grammarAccess.getExtensionSubStepAccess().getSubnumberAssignment_3(), "rule__ExtensionSubStep__SubnumberAssignment_3");
			builder.put(grammarAccess.getExtensionSubStepAccess().getTextAssignment_5(), "rule__ExtensionSubStep__TextAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;

	@Override
	protected InternalUseCaseDslParser createParser() {
		InternalUseCaseDslParser result = new InternalUseCaseDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UseCaseDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UseCaseDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
