/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.usecase.ide.contentassist.antlr.internal.InternalUseCaseDslParser;
import org.usecase.services.UseCaseDslGrammarAccess;

public class UseCaseDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UseCaseDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UseCaseDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUseCaseDescAccess().getGroup(), "rule__UseCaseDesc__Group__0");
			builder.put(grammarAccess.getModelAccess().getUsecasesAssignment(), "rule__Model__UsecasesAssignment");
			builder.put(grammarAccess.getUseCaseDescAccess().getNameAssignment_1(), "rule__UseCaseDesc__NameAssignment_1");
			builder.put(grammarAccess.getUseCaseDescAccess().getActorAssignment_3(), "rule__UseCaseDesc__ActorAssignment_3");
			builder.put(grammarAccess.getUseCaseDescAccess().getDescripcionAssignment_5(), "rule__UseCaseDesc__DescripcionAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;

	@Override
	protected InternalUseCaseDslParser createParser() {
		InternalUseCaseDslParser result = new InternalUseCaseDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UseCaseDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UseCaseDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
