/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.usecase.usecasedsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.usecase.usecasedsl.UsecasedslPackage
 * @generated
 */
public class UsecasedslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static UsecasedslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UsecasedslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = UsecasedslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UsecasedslSwitch<Adapter> modelSwitch =
    new UsecasedslSwitch<Adapter>()
    {
      @Override
      public Adapter caseUseCaseDescription(UseCaseDescription object)
      {
        return createUseCaseDescriptionAdapter();
      }
      @Override
      public Adapter caseBulletItem(BulletItem object)
      {
        return createBulletItemAdapter();
      }
      @Override
      public Adapter caseNumberedStep(NumberedStep object)
      {
        return createNumberedStepAdapter();
      }
      @Override
      public Adapter caseExtensionStep(ExtensionStep object)
      {
        return createExtensionStepAdapter();
      }
      @Override
      public Adapter caseExtensionSubStep(ExtensionSubStep object)
      {
        return createExtensionSubStepAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.usecase.usecasedsl.UseCaseDescription <em>Use Case Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.usecase.usecasedsl.UseCaseDescription
   * @generated
   */
  public Adapter createUseCaseDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.usecase.usecasedsl.BulletItem <em>Bullet Item</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.usecase.usecasedsl.BulletItem
   * @generated
   */
  public Adapter createBulletItemAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.usecase.usecasedsl.NumberedStep <em>Numbered Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.usecase.usecasedsl.NumberedStep
   * @generated
   */
  public Adapter createNumberedStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.usecase.usecasedsl.ExtensionStep <em>Extension Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.usecase.usecasedsl.ExtensionStep
   * @generated
   */
  public Adapter createExtensionStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.usecase.usecasedsl.ExtensionSubStep <em>Extension Sub Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.usecase.usecasedsl.ExtensionSubStep
   * @generated
   */
  public Adapter createExtensionSubStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //UsecasedslAdapterFactory
