/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedesc;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedesc.Model#getUsecases <em>Usecases</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedesc.UsecasedescPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Usecases</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedesc.UseCaseDesc}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usecases</em>' containment reference list.
   * @see org.usecase.usecasedesc.UsecasedescPackage#getModel_Usecases()
   * @model containment="true"
   * @generated
   */
  EList<UseCaseDesc> getUsecases();

} // Model
