/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedesc;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.usecase.usecasedesc.UsecasedescFactory
 * @model kind="package"
 * @generated
 */
public interface UsecasedescPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "usecasedesc";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/usecasedesc";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "usecasedesc";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UsecasedescPackage eINSTANCE = org.usecase.usecasedesc.impl.UsecasedescPackageImpl.init();

  /**
   * The meta object id for the '{@link org.usecase.usecasedesc.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedesc.impl.ModelImpl
   * @see org.usecase.usecasedesc.impl.UsecasedescPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Usecases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__USECASES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.usecase.usecasedesc.impl.UseCaseDescImpl <em>Use Case Desc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedesc.impl.UseCaseDescImpl
   * @see org.usecase.usecasedesc.impl.UsecasedescPackageImpl#getUseCaseDesc()
   * @generated
   */
  int USE_CASE_DESC = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESC__NAME = 0;

  /**
   * The feature id for the '<em><b>Actor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESC__ACTOR = 1;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESC__DESCRIPCION = 2;

  /**
   * The number of structural features of the '<em>Use Case Desc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESC_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.usecase.usecasedesc.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.usecase.usecasedesc.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedesc.Model#getUsecases <em>Usecases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Usecases</em>'.
   * @see org.usecase.usecasedesc.Model#getUsecases()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Usecases();

  /**
   * Returns the meta object for class '{@link org.usecase.usecasedesc.UseCaseDesc <em>Use Case Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Desc</em>'.
   * @see org.usecase.usecasedesc.UseCaseDesc
   * @generated
   */
  EClass getUseCaseDesc();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedesc.UseCaseDesc#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.usecase.usecasedesc.UseCaseDesc#getName()
   * @see #getUseCaseDesc()
   * @generated
   */
  EAttribute getUseCaseDesc_Name();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedesc.UseCaseDesc#getActor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Actor</em>'.
   * @see org.usecase.usecasedesc.UseCaseDesc#getActor()
   * @see #getUseCaseDesc()
   * @generated
   */
  EAttribute getUseCaseDesc_Actor();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedesc.UseCaseDesc#getDescripcion <em>Descripcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Descripcion</em>'.
   * @see org.usecase.usecasedesc.UseCaseDesc#getDescripcion()
   * @see #getUseCaseDesc()
   * @generated
   */
  EAttribute getUseCaseDesc_Descripcion();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UsecasedescFactory getUsecasedescFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.usecase.usecasedesc.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedesc.impl.ModelImpl
     * @see org.usecase.usecasedesc.impl.UsecasedescPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Usecases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__USECASES = eINSTANCE.getModel_Usecases();

    /**
     * The meta object literal for the '{@link org.usecase.usecasedesc.impl.UseCaseDescImpl <em>Use Case Desc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedesc.impl.UseCaseDescImpl
     * @see org.usecase.usecasedesc.impl.UsecasedescPackageImpl#getUseCaseDesc()
     * @generated
     */
    EClass USE_CASE_DESC = eINSTANCE.getUseCaseDesc();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESC__NAME = eINSTANCE.getUseCaseDesc_Name();

    /**
     * The meta object literal for the '<em><b>Actor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESC__ACTOR = eINSTANCE.getUseCaseDesc_Actor();

    /**
     * The meta object literal for the '<em><b>Descripcion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESC__DESCRIPCION = eINSTANCE.getUseCaseDesc_Descripcion();

  }

} //UsecasedescPackage
