/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedesc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Case Desc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedesc.UseCaseDesc#getName <em>Name</em>}</li>
 *   <li>{@link org.usecase.usecasedesc.UseCaseDesc#getActor <em>Actor</em>}</li>
 *   <li>{@link org.usecase.usecasedesc.UseCaseDesc#getDescripcion <em>Descripcion</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedesc.UsecasedescPackage#getUseCaseDesc()
 * @model
 * @generated
 */
public interface UseCaseDesc extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.usecase.usecasedesc.UsecasedescPackage#getUseCaseDesc_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.usecase.usecasedesc.UseCaseDesc#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Actor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' attribute.
   * @see #setActor(String)
   * @see org.usecase.usecasedesc.UsecasedescPackage#getUseCaseDesc_Actor()
   * @model
   * @generated
   */
  String getActor();

  /**
   * Sets the value of the '{@link org.usecase.usecasedesc.UseCaseDesc#getActor <em>Actor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor</em>' attribute.
   * @see #getActor()
   * @generated
   */
  void setActor(String value);

  /**
   * Returns the value of the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descripcion</em>' attribute.
   * @see #setDescripcion(String)
   * @see org.usecase.usecasedesc.UsecasedescPackage#getUseCaseDesc_Descripcion()
   * @model
   * @generated
   */
  String getDescripcion();

  /**
   * Sets the value of the '{@link org.usecase.usecasedesc.UseCaseDesc#getDescripcion <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descripcion</em>' attribute.
   * @see #getDescripcion()
   * @generated
   */
  void setDescripcion(String value);

} // UseCaseDesc
