/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bullet Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.BulletItem#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedsl.UsecasedslPackage#getBulletItem()
 * @model
 * @generated
 */
public interface BulletItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getBulletItem_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.BulletItem#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // BulletItem
