/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extension Sub Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.ExtensionSubStep#getNumber <em>Number</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionSubStep#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionSubStep#getSubnumber <em>Subnumber</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionSubStep#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionSubStep()
 * @model
 * @generated
 */
public interface ExtensionSubStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionSubStep_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionSubStep#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Letter</em>' attribute.
   * @see #setLetter(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionSubStep_Letter()
   * @model
   * @generated
   */
  String getLetter();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionSubStep#getLetter <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Letter</em>' attribute.
   * @see #getLetter()
   * @generated
   */
  void setLetter(String value);

  /**
   * Returns the value of the '<em><b>Subnumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subnumber</em>' attribute.
   * @see #setSubnumber(int)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionSubStep_Subnumber()
   * @model
   * @generated
   */
  int getSubnumber();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionSubStep#getSubnumber <em>Subnumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subnumber</em>' attribute.
   * @see #getSubnumber()
   * @generated
   */
  void setSubnumber(int value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionSubStep_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionSubStep#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // ExtensionSubStep
