/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extension Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.ExtensionStep#getNumber <em>Number</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionStep#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionStep#getText <em>Text</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.ExtensionStep#getSubsteps <em>Substeps</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionStep()
 * @model
 * @generated
 */
public interface ExtensionStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionStep_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionStep#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Letter</em>' attribute.
   * @see #setLetter(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionStep_Letter()
   * @model
   * @generated
   */
  String getLetter();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionStep#getLetter <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Letter</em>' attribute.
   * @see #getLetter()
   * @generated
   */
  void setLetter(String value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionStep_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.ExtensionStep#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Substeps</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.ExtensionSubStep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substeps</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getExtensionStep_Substeps()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionSubStep> getSubsteps();

} // ExtensionStep
