/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Case Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getName <em>Name</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getPrimaryActor <em>Primary Actor</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getStakeholders <em>Stakeholders</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getPostconditions <em>Postconditions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getMainSteps <em>Main Steps</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getExtensions <em>Extensions</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getSpecialRequirements <em>Special Requirements</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getTechnologyVariations <em>Technology Variations</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getFrequency <em>Frequency</em>}</li>
 *   <li>{@link org.usecase.usecasedsl.UseCaseDescription#getOpenIssues <em>Open Issues</em>}</li>
 * </ul>
 *
 * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription()
 * @model
 * @generated
 */
public interface UseCaseDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.UseCaseDescription#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Primary Actor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Actor</em>' attribute.
   * @see #setPrimaryActor(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_PrimaryActor()
   * @model
   * @generated
   */
  String getPrimaryActor();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.UseCaseDescription#getPrimaryActor <em>Primary Actor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Actor</em>' attribute.
   * @see #getPrimaryActor()
   * @generated
   */
  void setPrimaryActor(String value);

  /**
   * Returns the value of the '<em><b>Stakeholders</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stakeholders</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Stakeholders()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getStakeholders();

  /**
   * Returns the value of the '<em><b>Preconditions</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preconditions</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Preconditions()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getPreconditions();

  /**
   * Returns the value of the '<em><b>Postconditions</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postconditions</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Postconditions()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getPostconditions();

  /**
   * Returns the value of the '<em><b>Main Steps</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.NumberedStep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Steps</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_MainSteps()
   * @model containment="true"
   * @generated
   */
  EList<NumberedStep> getMainSteps();

  /**
   * Returns the value of the '<em><b>Extensions</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.ExtensionStep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extensions</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Extensions()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionStep> getExtensions();

  /**
   * Returns the value of the '<em><b>Special Requirements</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Special Requirements</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_SpecialRequirements()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getSpecialRequirements();

  /**
   * Returns the value of the '<em><b>Technology Variations</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Technology Variations</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_TechnologyVariations()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getTechnologyVariations();

  /**
   * Returns the value of the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frequency</em>' attribute.
   * @see #setFrequency(String)
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_Frequency()
   * @model
   * @generated
   */
  String getFrequency();

  /**
   * Sets the value of the '{@link org.usecase.usecasedsl.UseCaseDescription#getFrequency <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frequency</em>' attribute.
   * @see #getFrequency()
   * @generated
   */
  void setFrequency(String value);

  /**
   * Returns the value of the '<em><b>Open Issues</b></em>' containment reference list.
   * The list contents are of type {@link org.usecase.usecasedsl.BulletItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open Issues</em>' containment reference list.
   * @see org.usecase.usecasedsl.UsecasedslPackage#getUseCaseDescription_OpenIssues()
   * @model containment="true"
   * @generated
   */
  EList<BulletItem> getOpenIssues();

} // UseCaseDescription
