/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.usecase.usecasedsl.UsecasedslPackage
 * @generated
 */
public interface UsecasedslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UsecasedslFactory eINSTANCE = org.usecase.usecasedsl.impl.UsecasedslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Use Case Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Use Case Description</em>'.
   * @generated
   */
  UseCaseDescription createUseCaseDescription();

  /**
   * Returns a new object of class '<em>Bullet Item</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bullet Item</em>'.
   * @generated
   */
  BulletItem createBulletItem();

  /**
   * Returns a new object of class '<em>Numbered Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Numbered Step</em>'.
   * @generated
   */
  NumberedStep createNumberedStep();

  /**
   * Returns a new object of class '<em>Extension Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extension Step</em>'.
   * @generated
   */
  ExtensionStep createExtensionStep();

  /**
   * Returns a new object of class '<em>Extension Sub Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extension Sub Step</em>'.
   * @generated
   */
  ExtensionSubStep createExtensionSubStep();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UsecasedslPackage getUsecasedslPackage();

} //UsecasedslFactory
