/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.usecase.usecasedsl.UsecasedslFactory
 * @model kind="package"
 * @generated
 */
public interface UsecasedslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "usecasedsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.usecase.org/UseCaseDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "usecasedsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UsecasedslPackage eINSTANCE = org.usecase.usecasedsl.impl.UsecasedslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl <em>Use Case Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedsl.impl.UseCaseDescriptionImpl
   * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getUseCaseDescription()
   * @generated
   */
  int USE_CASE_DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Primary Actor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__PRIMARY_ACTOR = 1;

  /**
   * The feature id for the '<em><b>Stakeholders</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__STAKEHOLDERS = 2;

  /**
   * The feature id for the '<em><b>Preconditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__PRECONDITIONS = 3;

  /**
   * The feature id for the '<em><b>Postconditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__POSTCONDITIONS = 4;

  /**
   * The feature id for the '<em><b>Main Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__MAIN_STEPS = 5;

  /**
   * The feature id for the '<em><b>Extensions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__EXTENSIONS = 6;

  /**
   * The feature id for the '<em><b>Special Requirements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS = 7;

  /**
   * The feature id for the '<em><b>Technology Variations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS = 8;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__FREQUENCY = 9;

  /**
   * The feature id for the '<em><b>Open Issues</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION__OPEN_ISSUES = 10;

  /**
   * The number of structural features of the '<em>Use Case Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DESCRIPTION_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link org.usecase.usecasedsl.impl.BulletItemImpl <em>Bullet Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedsl.impl.BulletItemImpl
   * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getBulletItem()
   * @generated
   */
  int BULLET_ITEM = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_ITEM__TEXT = 0;

  /**
   * The number of structural features of the '<em>Bullet Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.usecase.usecasedsl.impl.NumberedStepImpl <em>Numbered Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedsl.impl.NumberedStepImpl
   * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getNumberedStep()
   * @generated
   */
  int NUMBERED_STEP = 2;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_STEP__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_STEP__TEXT = 1;

  /**
   * The number of structural features of the '<em>Numbered Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_STEP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.usecase.usecasedsl.impl.ExtensionStepImpl <em>Extension Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedsl.impl.ExtensionStepImpl
   * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getExtensionStep()
   * @generated
   */
  int EXTENSION_STEP = 3;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__LETTER = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__TEXT = 2;

  /**
   * The feature id for the '<em><b>Substeps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__SUBSTEPS = 3;

  /**
   * The number of structural features of the '<em>Extension Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl <em>Extension Sub Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.usecase.usecasedsl.impl.ExtensionSubStepImpl
   * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getExtensionSubStep()
   * @generated
   */
  int EXTENSION_SUB_STEP = 4;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_SUB_STEP__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_SUB_STEP__LETTER = 1;

  /**
   * The feature id for the '<em><b>Subnumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_SUB_STEP__SUBNUMBER = 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_SUB_STEP__TEXT = 3;

  /**
   * The number of structural features of the '<em>Extension Sub Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_SUB_STEP_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.usecase.usecasedsl.UseCaseDescription <em>Use Case Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Description</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription
   * @generated
   */
  EClass getUseCaseDescription();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.UseCaseDescription#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getName()
   * @see #getUseCaseDescription()
   * @generated
   */
  EAttribute getUseCaseDescription_Name();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.UseCaseDescription#getPrimaryActor <em>Primary Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Primary Actor</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getPrimaryActor()
   * @see #getUseCaseDescription()
   * @generated
   */
  EAttribute getUseCaseDescription_PrimaryActor();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getStakeholders <em>Stakeholders</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stakeholders</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getStakeholders()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_Stakeholders();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getPreconditions <em>Preconditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Preconditions</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getPreconditions()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_Preconditions();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getPostconditions <em>Postconditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Postconditions</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getPostconditions()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_Postconditions();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getMainSteps <em>Main Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Main Steps</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getMainSteps()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_MainSteps();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getExtensions <em>Extensions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Extensions</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getExtensions()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_Extensions();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getSpecialRequirements <em>Special Requirements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Special Requirements</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getSpecialRequirements()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_SpecialRequirements();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getTechnologyVariations <em>Technology Variations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Technology Variations</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getTechnologyVariations()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_TechnologyVariations();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.UseCaseDescription#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getFrequency()
   * @see #getUseCaseDescription()
   * @generated
   */
  EAttribute getUseCaseDescription_Frequency();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.UseCaseDescription#getOpenIssues <em>Open Issues</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Open Issues</em>'.
   * @see org.usecase.usecasedsl.UseCaseDescription#getOpenIssues()
   * @see #getUseCaseDescription()
   * @generated
   */
  EReference getUseCaseDescription_OpenIssues();

  /**
   * Returns the meta object for class '{@link org.usecase.usecasedsl.BulletItem <em>Bullet Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bullet Item</em>'.
   * @see org.usecase.usecasedsl.BulletItem
   * @generated
   */
  EClass getBulletItem();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.BulletItem#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.usecase.usecasedsl.BulletItem#getText()
   * @see #getBulletItem()
   * @generated
   */
  EAttribute getBulletItem_Text();

  /**
   * Returns the meta object for class '{@link org.usecase.usecasedsl.NumberedStep <em>Numbered Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numbered Step</em>'.
   * @see org.usecase.usecasedsl.NumberedStep
   * @generated
   */
  EClass getNumberedStep();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.NumberedStep#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.usecase.usecasedsl.NumberedStep#getNumber()
   * @see #getNumberedStep()
   * @generated
   */
  EAttribute getNumberedStep_Number();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.NumberedStep#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.usecase.usecasedsl.NumberedStep#getText()
   * @see #getNumberedStep()
   * @generated
   */
  EAttribute getNumberedStep_Text();

  /**
   * Returns the meta object for class '{@link org.usecase.usecasedsl.ExtensionStep <em>Extension Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extension Step</em>'.
   * @see org.usecase.usecasedsl.ExtensionStep
   * @generated
   */
  EClass getExtensionStep();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionStep#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.usecase.usecasedsl.ExtensionStep#getNumber()
   * @see #getExtensionStep()
   * @generated
   */
  EAttribute getExtensionStep_Number();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionStep#getLetter <em>Letter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Letter</em>'.
   * @see org.usecase.usecasedsl.ExtensionStep#getLetter()
   * @see #getExtensionStep()
   * @generated
   */
  EAttribute getExtensionStep_Letter();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionStep#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.usecase.usecasedsl.ExtensionStep#getText()
   * @see #getExtensionStep()
   * @generated
   */
  EAttribute getExtensionStep_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.usecase.usecasedsl.ExtensionStep#getSubsteps <em>Substeps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Substeps</em>'.
   * @see org.usecase.usecasedsl.ExtensionStep#getSubsteps()
   * @see #getExtensionStep()
   * @generated
   */
  EReference getExtensionStep_Substeps();

  /**
   * Returns the meta object for class '{@link org.usecase.usecasedsl.ExtensionSubStep <em>Extension Sub Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extension Sub Step</em>'.
   * @see org.usecase.usecasedsl.ExtensionSubStep
   * @generated
   */
  EClass getExtensionSubStep();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionSubStep#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.usecase.usecasedsl.ExtensionSubStep#getNumber()
   * @see #getExtensionSubStep()
   * @generated
   */
  EAttribute getExtensionSubStep_Number();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionSubStep#getLetter <em>Letter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Letter</em>'.
   * @see org.usecase.usecasedsl.ExtensionSubStep#getLetter()
   * @see #getExtensionSubStep()
   * @generated
   */
  EAttribute getExtensionSubStep_Letter();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionSubStep#getSubnumber <em>Subnumber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subnumber</em>'.
   * @see org.usecase.usecasedsl.ExtensionSubStep#getSubnumber()
   * @see #getExtensionSubStep()
   * @generated
   */
  EAttribute getExtensionSubStep_Subnumber();

  /**
   * Returns the meta object for the attribute '{@link org.usecase.usecasedsl.ExtensionSubStep#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.usecase.usecasedsl.ExtensionSubStep#getText()
   * @see #getExtensionSubStep()
   * @generated
   */
  EAttribute getExtensionSubStep_Text();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UsecasedslFactory getUsecasedslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.usecase.usecasedsl.impl.UseCaseDescriptionImpl <em>Use Case Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedsl.impl.UseCaseDescriptionImpl
     * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getUseCaseDescription()
     * @generated
     */
    EClass USE_CASE_DESCRIPTION = eINSTANCE.getUseCaseDescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESCRIPTION__NAME = eINSTANCE.getUseCaseDescription_Name();

    /**
     * The meta object literal for the '<em><b>Primary Actor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESCRIPTION__PRIMARY_ACTOR = eINSTANCE.getUseCaseDescription_PrimaryActor();

    /**
     * The meta object literal for the '<em><b>Stakeholders</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__STAKEHOLDERS = eINSTANCE.getUseCaseDescription_Stakeholders();

    /**
     * The meta object literal for the '<em><b>Preconditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__PRECONDITIONS = eINSTANCE.getUseCaseDescription_Preconditions();

    /**
     * The meta object literal for the '<em><b>Postconditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__POSTCONDITIONS = eINSTANCE.getUseCaseDescription_Postconditions();

    /**
     * The meta object literal for the '<em><b>Main Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__MAIN_STEPS = eINSTANCE.getUseCaseDescription_MainSteps();

    /**
     * The meta object literal for the '<em><b>Extensions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__EXTENSIONS = eINSTANCE.getUseCaseDescription_Extensions();

    /**
     * The meta object literal for the '<em><b>Special Requirements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__SPECIAL_REQUIREMENTS = eINSTANCE.getUseCaseDescription_SpecialRequirements();

    /**
     * The meta object literal for the '<em><b>Technology Variations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__TECHNOLOGY_VARIATIONS = eINSTANCE.getUseCaseDescription_TechnologyVariations();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_DESCRIPTION__FREQUENCY = eINSTANCE.getUseCaseDescription_Frequency();

    /**
     * The meta object literal for the '<em><b>Open Issues</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DESCRIPTION__OPEN_ISSUES = eINSTANCE.getUseCaseDescription_OpenIssues();

    /**
     * The meta object literal for the '{@link org.usecase.usecasedsl.impl.BulletItemImpl <em>Bullet Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedsl.impl.BulletItemImpl
     * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getBulletItem()
     * @generated
     */
    EClass BULLET_ITEM = eINSTANCE.getBulletItem();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BULLET_ITEM__TEXT = eINSTANCE.getBulletItem_Text();

    /**
     * The meta object literal for the '{@link org.usecase.usecasedsl.impl.NumberedStepImpl <em>Numbered Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedsl.impl.NumberedStepImpl
     * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getNumberedStep()
     * @generated
     */
    EClass NUMBERED_STEP = eINSTANCE.getNumberedStep();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERED_STEP__NUMBER = eINSTANCE.getNumberedStep_Number();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERED_STEP__TEXT = eINSTANCE.getNumberedStep_Text();

    /**
     * The meta object literal for the '{@link org.usecase.usecasedsl.impl.ExtensionStepImpl <em>Extension Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedsl.impl.ExtensionStepImpl
     * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getExtensionStep()
     * @generated
     */
    EClass EXTENSION_STEP = eINSTANCE.getExtensionStep();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_STEP__NUMBER = eINSTANCE.getExtensionStep_Number();

    /**
     * The meta object literal for the '<em><b>Letter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_STEP__LETTER = eINSTANCE.getExtensionStep_Letter();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_STEP__TEXT = eINSTANCE.getExtensionStep_Text();

    /**
     * The meta object literal for the '<em><b>Substeps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION_STEP__SUBSTEPS = eINSTANCE.getExtensionStep_Substeps();

    /**
     * The meta object literal for the '{@link org.usecase.usecasedsl.impl.ExtensionSubStepImpl <em>Extension Sub Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.usecase.usecasedsl.impl.ExtensionSubStepImpl
     * @see org.usecase.usecasedsl.impl.UsecasedslPackageImpl#getExtensionSubStep()
     * @generated
     */
    EClass EXTENSION_SUB_STEP = eINSTANCE.getExtensionSubStep();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_SUB_STEP__NUMBER = eINSTANCE.getExtensionSubStep_Number();

    /**
     * The meta object literal for the '<em><b>Letter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_SUB_STEP__LETTER = eINSTANCE.getExtensionSubStep_Letter();

    /**
     * The meta object literal for the '<em><b>Subnumber</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_SUB_STEP__SUBNUMBER = eINSTANCE.getExtensionSubStep_Subnumber();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_SUB_STEP__TEXT = eINSTANCE.getExtensionSubStep_Text();

  }

} //UsecasedslPackage
