/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ui.contentassist;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.usecase.usecase.Actor;
import org.usecase.usecase.Association;
import org.usecase.usecase.Model;
import org.usecase.usecase.Relation;
import org.usecase.usecase.UseCase;
import org.usecase.usecase.UsecasePackage;
import org.usecase.usecasedsl.UseCaseDescription;

public class UseCaseDslProposalProvider extends AbstractUseCaseDslProposalProvider {
	
	private URI findUseCaseModelUri(UseCaseDescription desc) {
	    if (desc.eResource() == null || desc.eResource().getURI() == null) {
	        return null;
	    }

	    URI descUri = desc.eResource().getURI();

	    if (!descUri.isPlatformResource()) {
	        return null;
	    }

	    String projectName = descUri.segment(1);

	    IProject project = ResourcesPlugin.getWorkspace()
	            .getRoot()
	            .getProject(projectName);

	    if (project == null || !project.exists()) {
	        return null;
	    }

	    final URI[] result = new URI[1];

	    try {
	        project.accept(resource -> {
	            if (result[0] != null) {
	                return false;
	            }

	            if (resource instanceof IFile) {
	                IFile file = (IFile) resource;

	                if ("usecase".equals(file.getFileExtension())) {
	                    result[0] = URI.createPlatformResourceURI(
	                            file.getFullPath().toString(),
	                            true
	                    );
	                    return false;
	                }
	            }

	            return true;
	        });
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

	    return result[0];
	}

    @Override
    public void completeUseCaseDescription_PrimaryActor(
            EObject model,
            Assignment assignment,
            ContentAssistContext context,
            ICompletionProposalAcceptor acceptor) {
    	
    	System.out.println("CONTENT ASSIST PRIMARY ACTOR");

        if (!(model instanceof UseCaseDescription)) {
        	System.out.println("pos me voy");
            super.completeUseCaseDescription_PrimaryActor(model, assignment, context, acceptor);
            return;
        }

        UseCaseDescription description = (UseCaseDescription) model;

        List<String> associatedActors = getAssociatedActorNames(description);

        for (String actorName : associatedActors) {
           
            acceptor.accept(
                createCompletionProposal(
                    "\"" + actorName + "\"",
                    actorName,
                    null,
                    context
                )
            );
        }
    }

    private List<String> getAssociatedActorNames(UseCaseDescription description) {
        List<String> actorNames = new ArrayList<>();

        Model diagramModel = loadDiagramModel(description);

        if (diagramModel == null || description.getName() == null) {
            return actorNames;
        }

        UseCase currentUseCase = findUseCaseByName(diagramModel, description.getName());

        if (currentUseCase == null) {
            return actorNames;
        }

        for (Relation relation : diagramModel.getRelations()) {
            if (relation instanceof Association) {
                EObject source = relation.getSource();
                EObject target = relation.getTarget();

                if (source instanceof Actor && target == currentUseCase) {
                    Actor actor = (Actor) source;
                    if (actor.getName() != null && !actor.getName().isBlank()) {
                        actorNames.add(actor.getName());
                    }
                }

                if (target instanceof Actor && source == currentUseCase) {
                    Actor actor = (Actor) target;
                    if (actor.getName() != null && !actor.getName().isBlank()) {
                        actorNames.add(actor.getName());
                    }
                }
            }
        }

        return actorNames;
    }

    private UseCase findUseCaseByName(Model model, String useCaseName) {
        for (EObject element : model.getElements()) {
            if (element instanceof UseCase) {
                UseCase useCase = (UseCase) element;

                if (useCaseName.equals(useCase.getName())) {
                    return useCase;
                }
            }
        }

        return null;
    }

    private Model loadDiagramModel(UseCaseDescription description) {
        try {
            if (description.eResource() == null || description.eResource().getURI() == null) {
                return null;
            }

            URI descUri = description.eResource().getURI();

            if (!descUri.isPlatformResource()) {
                return null;
            }

            String projectName = descUri.segment(0);

            URI modelUri = findUseCaseModelUri(description);

            if (modelUri == null) {
                return null;
            }

            ResourceSet resourceSet = new ResourceSetImpl();

            resourceSet.getPackageRegistry().put(
                    UsecasePackage.eNS_URI,
                    UsecasePackage.eINSTANCE
            );

            resourceSet.getResourceFactoryRegistry()
                    .getExtensionToFactoryMap()
                    .put("usecase", new XMIResourceFactoryImpl());

            Resource resource = resourceSet.getResource(modelUri, true);

            if (resource == null || resource.getContents().isEmpty()) {
                return null;
            }

            Object root = resource.getContents().get(0);

            if (root instanceof Model) {
                return (Model) root;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }
}
