/*
 * generated by Xtext 2.34.0
 */
package org.usecase.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UseCaseDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class UseCaseDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.UseCaseDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUseCaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cPrimaryActorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPrimaryActorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrimaryActorSTRINGTerminalRuleCall_3_0 = (RuleCall)cPrimaryActorAssignment_3.eContents().get(0);
		private final Keyword cStakeholdersAndGoalsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStakeholdersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStakeholdersBulletItemParserRuleCall_5_0 = (RuleCall)cStakeholdersAssignment_5.eContents().get(0);
		private final Keyword cPreconditionsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPreconditionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPreconditionsBulletItemParserRuleCall_7_0 = (RuleCall)cPreconditionsAssignment_7.eContents().get(0);
		private final Keyword cPostconditionsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cPostconditionsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cPostconditionsBulletItemParserRuleCall_9_0 = (RuleCall)cPostconditionsAssignment_9.eContents().get(0);
		private final Keyword cMainFlowKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMainStepsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMainStepsNumberedStepParserRuleCall_11_0 = (RuleCall)cMainStepsAssignment_11.eContents().get(0);
		private final Keyword cExtensionsKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cExtensionsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cExtensionsExtensionStepParserRuleCall_13_0 = (RuleCall)cExtensionsAssignment_13.eContents().get(0);
		private final Keyword cSpecialRequirementsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cSpecialRequirementsAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cSpecialRequirementsBulletItemParserRuleCall_15_0 = (RuleCall)cSpecialRequirementsAssignment_15.eContents().get(0);
		private final Keyword cTechnologyAndDataVariationsKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cTechnologyVariationsAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cTechnologyVariationsBulletItemParserRuleCall_17_0 = (RuleCall)cTechnologyVariationsAssignment_17.eContents().get(0);
		private final Keyword cFrequencyOfOccurrenceKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cFrequencyAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cFrequencySTRINGTerminalRuleCall_19_0 = (RuleCall)cFrequencyAssignment_19.eContents().get(0);
		private final Keyword cOpenIssuesKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cOpenIssuesAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cOpenIssuesBulletItemParserRuleCall_21_0 = (RuleCall)cOpenIssuesAssignment_21.eContents().get(0);
		
		//UseCaseDescription:
		//    'useCase' name=STRING
		//    'primaryActor:' primaryActor=STRING
		//    'stakeholdersAndGoals:'
		//        stakeholders+=BulletItem*
		//    'preconditions:'
		//        preconditions+=BulletItem*
		//    'postconditions:'
		//        postconditions+=BulletItem*
		//    'mainFlow:'
		//        mainSteps+=NumberedStep*
		//    'extensions:'
		//        extensions+=ExtensionStep*
		//    'specialRequirements:'
		//        specialRequirements+=BulletItem*
		//    'technologyAndDataVariations:'
		//        technologyVariations+=BulletItem*
		//    'frequencyOfOccurrence:' frequency=STRING
		//    'openIssues:'
		//        openIssues+=BulletItem*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'useCase' name=STRING
		//'primaryActor:' primaryActor=STRING
		//'stakeholdersAndGoals:'
		//    stakeholders+=BulletItem*
		//'preconditions:'
		//    preconditions+=BulletItem*
		//'postconditions:'
		//    postconditions+=BulletItem*
		//'mainFlow:'
		//    mainSteps+=NumberedStep*
		//'extensions:'
		//    extensions+=ExtensionStep*
		//'specialRequirements:'
		//    specialRequirements+=BulletItem*
		//'technologyAndDataVariations:'
		//    technologyVariations+=BulletItem*
		//'frequencyOfOccurrence:' frequency=STRING
		//'openIssues:'
		//    openIssues+=BulletItem*
		public Group getGroup() { return cGroup; }
		
		//'useCase'
		public Keyword getUseCaseKeyword_0() { return cUseCaseKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'primaryActor:'
		public Keyword getPrimaryActorKeyword_2() { return cPrimaryActorKeyword_2; }
		
		//primaryActor=STRING
		public Assignment getPrimaryActorAssignment_3() { return cPrimaryActorAssignment_3; }
		
		//STRING
		public RuleCall getPrimaryActorSTRINGTerminalRuleCall_3_0() { return cPrimaryActorSTRINGTerminalRuleCall_3_0; }
		
		//'stakeholdersAndGoals:'
		public Keyword getStakeholdersAndGoalsKeyword_4() { return cStakeholdersAndGoalsKeyword_4; }
		
		//stakeholders+=BulletItem*
		public Assignment getStakeholdersAssignment_5() { return cStakeholdersAssignment_5; }
		
		//BulletItem
		public RuleCall getStakeholdersBulletItemParserRuleCall_5_0() { return cStakeholdersBulletItemParserRuleCall_5_0; }
		
		//'preconditions:'
		public Keyword getPreconditionsKeyword_6() { return cPreconditionsKeyword_6; }
		
		//preconditions+=BulletItem*
		public Assignment getPreconditionsAssignment_7() { return cPreconditionsAssignment_7; }
		
		//BulletItem
		public RuleCall getPreconditionsBulletItemParserRuleCall_7_0() { return cPreconditionsBulletItemParserRuleCall_7_0; }
		
		//'postconditions:'
		public Keyword getPostconditionsKeyword_8() { return cPostconditionsKeyword_8; }
		
		//postconditions+=BulletItem*
		public Assignment getPostconditionsAssignment_9() { return cPostconditionsAssignment_9; }
		
		//BulletItem
		public RuleCall getPostconditionsBulletItemParserRuleCall_9_0() { return cPostconditionsBulletItemParserRuleCall_9_0; }
		
		//'mainFlow:'
		public Keyword getMainFlowKeyword_10() { return cMainFlowKeyword_10; }
		
		//mainSteps+=NumberedStep*
		public Assignment getMainStepsAssignment_11() { return cMainStepsAssignment_11; }
		
		//NumberedStep
		public RuleCall getMainStepsNumberedStepParserRuleCall_11_0() { return cMainStepsNumberedStepParserRuleCall_11_0; }
		
		//'extensions:'
		public Keyword getExtensionsKeyword_12() { return cExtensionsKeyword_12; }
		
		//extensions+=ExtensionStep*
		public Assignment getExtensionsAssignment_13() { return cExtensionsAssignment_13; }
		
		//ExtensionStep
		public RuleCall getExtensionsExtensionStepParserRuleCall_13_0() { return cExtensionsExtensionStepParserRuleCall_13_0; }
		
		//'specialRequirements:'
		public Keyword getSpecialRequirementsKeyword_14() { return cSpecialRequirementsKeyword_14; }
		
		//specialRequirements+=BulletItem*
		public Assignment getSpecialRequirementsAssignment_15() { return cSpecialRequirementsAssignment_15; }
		
		//BulletItem
		public RuleCall getSpecialRequirementsBulletItemParserRuleCall_15_0() { return cSpecialRequirementsBulletItemParserRuleCall_15_0; }
		
		//'technologyAndDataVariations:'
		public Keyword getTechnologyAndDataVariationsKeyword_16() { return cTechnologyAndDataVariationsKeyword_16; }
		
		//technologyVariations+=BulletItem*
		public Assignment getTechnologyVariationsAssignment_17() { return cTechnologyVariationsAssignment_17; }
		
		//BulletItem
		public RuleCall getTechnologyVariationsBulletItemParserRuleCall_17_0() { return cTechnologyVariationsBulletItemParserRuleCall_17_0; }
		
		//'frequencyOfOccurrence:'
		public Keyword getFrequencyOfOccurrenceKeyword_18() { return cFrequencyOfOccurrenceKeyword_18; }
		
		//frequency=STRING
		public Assignment getFrequencyAssignment_19() { return cFrequencyAssignment_19; }
		
		//STRING
		public RuleCall getFrequencySTRINGTerminalRuleCall_19_0() { return cFrequencySTRINGTerminalRuleCall_19_0; }
		
		//'openIssues:'
		public Keyword getOpenIssuesKeyword_20() { return cOpenIssuesKeyword_20; }
		
		//openIssues+=BulletItem*
		public Assignment getOpenIssuesAssignment_21() { return cOpenIssuesAssignment_21; }
		
		//BulletItem
		public RuleCall getOpenIssuesBulletItemParserRuleCall_21_0() { return cOpenIssuesBulletItemParserRuleCall_21_0; }
	}
	public class BulletItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.BulletItem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//BulletItem:
		//    '-' text=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'-' text=STRING
		public Group getGroup() { return cGroup; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
	}
	public class NumberedStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.NumberedStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNumberAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_0_0 = (RuleCall)cNumberAssignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		
		//NumberedStep:
		//    number=INT '.' text=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//number=INT '.' text=STRING
		public Group getGroup() { return cGroup; }
		
		//number=INT
		public Assignment getNumberAssignment_0() { return cNumberAssignment_0; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_0_0() { return cNumberINTTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
	}
	public class ExtensionStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.ExtensionStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNumberAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_0_0 = (RuleCall)cNumberAssignment_0.eContents().get(0);
		private final Assignment cLetterAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLetterIDTerminalRuleCall_1_0 = (RuleCall)cLetterAssignment_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Assignment cSubstepsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSubstepsExtensionSubStepParserRuleCall_4_0 = (RuleCall)cSubstepsAssignment_4.eContents().get(0);
		
		//ExtensionStep:
		//    number=INT letter=ID '.' text=STRING
		//    substeps+=ExtensionSubStep*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//number=INT letter=ID '.' text=STRING
		//substeps+=ExtensionSubStep*
		public Group getGroup() { return cGroup; }
		
		//number=INT
		public Assignment getNumberAssignment_0() { return cNumberAssignment_0; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_0_0() { return cNumberINTTerminalRuleCall_0_0; }
		
		//letter=ID
		public Assignment getLetterAssignment_1() { return cLetterAssignment_1; }
		
		//ID
		public RuleCall getLetterIDTerminalRuleCall_1_0() { return cLetterIDTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//text=STRING
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0() { return cTextSTRINGTerminalRuleCall_3_0; }
		
		//substeps+=ExtensionSubStep*
		public Assignment getSubstepsAssignment_4() { return cSubstepsAssignment_4; }
		
		//ExtensionSubStep
		public RuleCall getSubstepsExtensionSubStepParserRuleCall_4_0() { return cSubstepsExtensionSubStepParserRuleCall_4_0; }
	}
	public class ExtensionSubStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.ExtensionSubStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNumberAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_0_0 = (RuleCall)cNumberAssignment_0.eContents().get(0);
		private final Assignment cLetterAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLetterIDTerminalRuleCall_1_0 = (RuleCall)cLetterAssignment_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSubnumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSubnumberINTTerminalRuleCall_3_0 = (RuleCall)cSubnumberAssignment_3.eContents().get(0);
		private final Keyword cFullStopKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTextAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_0 = (RuleCall)cTextAssignment_5.eContents().get(0);
		
		//ExtensionSubStep:
		//    number=INT letter=ID '.' subnumber=INT '.' text=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//number=INT letter=ID '.' subnumber=INT '.' text=STRING
		public Group getGroup() { return cGroup; }
		
		//number=INT
		public Assignment getNumberAssignment_0() { return cNumberAssignment_0; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_0_0() { return cNumberINTTerminalRuleCall_0_0; }
		
		//letter=ID
		public Assignment getLetterAssignment_1() { return cLetterAssignment_1; }
		
		//ID
		public RuleCall getLetterIDTerminalRuleCall_1_0() { return cLetterIDTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//subnumber=INT
		public Assignment getSubnumberAssignment_3() { return cSubnumberAssignment_3; }
		
		//INT
		public RuleCall getSubnumberINTTerminalRuleCall_3_0() { return cSubnumberINTTerminalRuleCall_3_0; }
		
		//'.'
		public Keyword getFullStopKeyword_4() { return cFullStopKeyword_4; }
		
		//text=STRING
		public Assignment getTextAssignment_5() { return cTextAssignment_5; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_0() { return cTextSTRINGTerminalRuleCall_5_0; }
	}
	
	
	private final UseCaseDescriptionElements pUseCaseDescription;
	private final BulletItemElements pBulletItem;
	private final NumberedStepElements pNumberedStep;
	private final ExtensionStepElements pExtensionStep;
	private final ExtensionSubStepElements pExtensionSubStep;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UseCaseDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUseCaseDescription = new UseCaseDescriptionElements();
		this.pBulletItem = new BulletItemElements();
		this.pNumberedStep = new NumberedStepElements();
		this.pExtensionStep = new ExtensionStepElements();
		this.pExtensionSubStep = new ExtensionSubStepElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.usecase.UseCaseDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//UseCaseDescription:
	//    'useCase' name=STRING
	//    'primaryActor:' primaryActor=STRING
	//    'stakeholdersAndGoals:'
	//        stakeholders+=BulletItem*
	//    'preconditions:'
	//        preconditions+=BulletItem*
	//    'postconditions:'
	//        postconditions+=BulletItem*
	//    'mainFlow:'
	//        mainSteps+=NumberedStep*
	//    'extensions:'
	//        extensions+=ExtensionStep*
	//    'specialRequirements:'
	//        specialRequirements+=BulletItem*
	//    'technologyAndDataVariations:'
	//        technologyVariations+=BulletItem*
	//    'frequencyOfOccurrence:' frequency=STRING
	//    'openIssues:'
	//        openIssues+=BulletItem*
	//;
	public UseCaseDescriptionElements getUseCaseDescriptionAccess() {
		return pUseCaseDescription;
	}
	
	public ParserRule getUseCaseDescriptionRule() {
		return getUseCaseDescriptionAccess().getRule();
	}
	
	//BulletItem:
	//    '-' text=STRING
	//;
	public BulletItemElements getBulletItemAccess() {
		return pBulletItem;
	}
	
	public ParserRule getBulletItemRule() {
		return getBulletItemAccess().getRule();
	}
	
	//NumberedStep:
	//    number=INT '.' text=STRING
	//;
	public NumberedStepElements getNumberedStepAccess() {
		return pNumberedStep;
	}
	
	public ParserRule getNumberedStepRule() {
		return getNumberedStepAccess().getRule();
	}
	
	//ExtensionStep:
	//    number=INT letter=ID '.' text=STRING
	//    substeps+=ExtensionSubStep*
	//;
	public ExtensionStepElements getExtensionStepAccess() {
		return pExtensionStep;
	}
	
	public ParserRule getExtensionStepRule() {
		return getExtensionStepAccess().getRule();
	}
	
	//ExtensionSubStep:
	//    number=INT letter=ID '.' subnumber=INT '.' text=STRING
	//;
	public ExtensionSubStepElements getExtensionSubStepAccess() {
		return pExtensionSubStep;
	}
	
	public ParserRule getExtensionSubStepRule() {
		return getExtensionSubStepAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
