/*
 * generated by Xtext 2.34.0
 */
package org.usecase.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UseCaseDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.Model");
		private final Assignment cUsecasesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cUsecasesUseCaseDescParserRuleCall_0 = (RuleCall)cUsecasesAssignment.eContents().get(0);
		
		//Model:
		//    usecases+=UseCaseDesc*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//usecases+=UseCaseDesc*
		public Assignment getUsecasesAssignment() { return cUsecasesAssignment; }
		
		//UseCaseDesc
		public RuleCall getUsecasesUseCaseDescParserRuleCall_0() { return cUsecasesUseCaseDescParserRuleCall_0; }
	}
	public class UseCaseDescElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.usecase.UseCaseDsl.UseCaseDesc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUsecaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cActorPrimarioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActorIDTerminalRuleCall_3_0 = (RuleCall)cActorAssignment_3.eContents().get(0);
		private final Keyword cDescripcionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescripcionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescripcionAssignment_5.eContents().get(0);
		
		//UseCaseDesc:
		//    'usecase' name=ID
		//    'actorPrimario:' actor=ID
		//    'descripcion:' descripcion=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'usecase' name=ID
		//'actorPrimario:' actor=ID
		//'descripcion:' descripcion=STRING
		public Group getGroup() { return cGroup; }
		
		//'usecase'
		public Keyword getUsecaseKeyword_0() { return cUsecaseKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'actorPrimario:'
		public Keyword getActorPrimarioKeyword_2() { return cActorPrimarioKeyword_2; }
		
		//actor=ID
		public Assignment getActorAssignment_3() { return cActorAssignment_3; }
		
		//ID
		public RuleCall getActorIDTerminalRuleCall_3_0() { return cActorIDTerminalRuleCall_3_0; }
		
		//'descripcion:'
		public Keyword getDescripcionKeyword_4() { return cDescripcionKeyword_4; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_5() { return cDescripcionAssignment_5; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_5_0() { return cDescripcionSTRINGTerminalRuleCall_5_0; }
	}
	
	
	private final ModelElements pModel;
	private final UseCaseDescElements pUseCaseDesc;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UseCaseDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pUseCaseDesc = new UseCaseDescElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.usecase.UseCaseDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    usecases+=UseCaseDesc*
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//UseCaseDesc:
	//    'usecase' name=ID
	//    'actorPrimario:' actor=ID
	//    'descripcion:' descripcion=STRING
	//;
	public UseCaseDescElements getUseCaseDescAccess() {
		return pUseCaseDesc;
	}
	
	public ParserRule getUseCaseDescRule() {
		return getUseCaseDescAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
