/*
 * generated by Xtext 2.34.0
 */
package org.usecase.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUseCaseDslScopeProvider extends DelegatingScopeProvider {
}
