/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UseCaseDescUiModule extends AbstractUseCaseDescUiModule {

	public UseCaseDescUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
