/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.usecase.UseCaseDescRuntimeModule;
import org.usecase.UseCaseDescStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UseCaseDescIdeSetup extends UseCaseDescStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UseCaseDescRuntimeModule(), new UseCaseDescIdeModule()));
	}
	
}
