/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.usecase.UseCaseDslRuntimeModule;
import org.usecase.UseCaseDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UseCaseDslIdeSetup extends UseCaseDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UseCaseDslRuntimeModule(), new UseCaseDslIdeModule()));
	}
	
}
