/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedesc.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.usecase.usecasedesc.Model;
import org.usecase.usecasedesc.UseCaseDesc;
import org.usecase.usecasedesc.UsecasedescFactory;
import org.usecase.usecasedesc.UsecasedescPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UsecasedescPackageImpl extends EPackageImpl implements UsecasedescPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass useCaseDescEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.usecase.usecasedesc.UsecasedescPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private UsecasedescPackageImpl()
  {
    super(eNS_URI, UsecasedescFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link UsecasedescPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static UsecasedescPackage init()
  {
    if (isInited) return (UsecasedescPackage)EPackage.Registry.INSTANCE.getEPackage(UsecasedescPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredUsecasedescPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    UsecasedescPackageImpl theUsecasedescPackage = registeredUsecasedescPackage instanceof UsecasedescPackageImpl ? (UsecasedescPackageImpl)registeredUsecasedescPackage : new UsecasedescPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theUsecasedescPackage.createPackageContents();

    // Initialize created meta-data
    theUsecasedescPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theUsecasedescPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(UsecasedescPackage.eNS_URI, theUsecasedescPackage);
    return theUsecasedescPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Usecases()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUseCaseDesc()
  {
    return useCaseDescEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDesc_Name()
  {
    return (EAttribute)useCaseDescEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDesc_Actor()
  {
    return (EAttribute)useCaseDescEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUseCaseDesc_Descripcion()
  {
    return (EAttribute)useCaseDescEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsecasedescFactory getUsecasedescFactory()
  {
    return (UsecasedescFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__USECASES);

    useCaseDescEClass = createEClass(USE_CASE_DESC);
    createEAttribute(useCaseDescEClass, USE_CASE_DESC__NAME);
    createEAttribute(useCaseDescEClass, USE_CASE_DESC__ACTOR);
    createEAttribute(useCaseDescEClass, USE_CASE_DESC__DESCRIPCION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Usecases(), this.getUseCaseDesc(), null, "usecases", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(useCaseDescEClass, UseCaseDesc.class, "UseCaseDesc", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUseCaseDesc_Name(), ecorePackage.getEString(), "name", null, 0, 1, UseCaseDesc.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUseCaseDesc_Actor(), ecorePackage.getEString(), "actor", null, 0, 1, UseCaseDesc.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUseCaseDesc_Descripcion(), ecorePackage.getEString(), "descripcion", null, 0, 1, UseCaseDesc.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //UsecasedescPackageImpl
