/**
 * generated by Xtext 2.34.0
 */
package org.usecase.usecasedesc.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.usecase.usecasedesc.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UsecasedescFactoryImpl extends EFactoryImpl implements UsecasedescFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static UsecasedescFactory init()
  {
    try
    {
      UsecasedescFactory theUsecasedescFactory = (UsecasedescFactory)EPackage.Registry.INSTANCE.getEFactory(UsecasedescPackage.eNS_URI);
      if (theUsecasedescFactory != null)
      {
        return theUsecasedescFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new UsecasedescFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UsecasedescFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case UsecasedescPackage.MODEL: return createModel();
      case UsecasedescPackage.USE_CASE_DESC: return createUseCaseDesc();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UseCaseDesc createUseCaseDesc()
  {
    UseCaseDescImpl useCaseDesc = new UseCaseDescImpl();
    return useCaseDesc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsecasedescPackage getUsecasedescPackage()
  {
    return (UsecasedescPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static UsecasedescPackage getPackage()
  {
    return UsecasedescPackage.eINSTANCE;
  }

} //UsecasedescFactoryImpl
