/*
 * generated by Xtext 2.34.0
 */
package org.usecase.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.usecase.xtext.ui.internal.XtextActivator;

public class UseCaseDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.usecase.UseCaseDsl");
	}

}
