/**
 * generated by Xtext 2.34.0
 */
package org.usecase.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.usecase.usecasedesc.Model;

@RunWith(XtextRunner.class)/* 
@InjectWith(_UseCaseDescInjectorProvider) */
@SuppressWarnings("all")
public class UseCaseDescParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nAccess restriction: The type Assert is not accessible due to restriction on required project org.usecase.xtext.tests"
      + "\nAccess restriction: The type Assert is not accessible due to restriction on required project org.usecase.xtext.tests");
  }
}
