/**
 * generated by Xtext 2.34.0
 */
package org.usecase.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(UseCaseDslInjectorProvider.class)
@SuppressWarnings("all")
public class UseCaseDslParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field UseCaseDslParsingTest.parseHelper refers to the missing type Model"
      + "\nAccess restriction: The type Assert is not accessible due to restriction on required project org.usecase.xtext.tests"
      + "\nAccess restriction: The type Assert is not accessible due to restriction on required project org.usecase.xtext.tests"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
